### ISSUE TITLE
Error: React/RCTEventDispatcher.h not found in iOS

### ISSUE THREAD

**Issue by ikzjfr0** [kmagiera/react-native-gesture-handler#179]
Following the instruction via:
1. yarn react-native-gesture-handler
2. react-native link react-native-gesture-handler

Then I compiled my Xcode project and got an issue:
`Error: React/RCTEventDispatcher.h not found`
![image](https://user-images.githubusercontent.com/6456056/40276034-116a5cb2-5c43-11e8-8069-3c11415e851b.png)

My environment is:
"react": "16.3.2",
"react-native": "0.55.3",
"react-native-gesture-handler": "^1.0.0",

By the way, is there a pod that I can use for `Cocoapod` in iOS?

**Comment by osdnk** [comment]
@ikzjfr0, Did you try 'clean' in Xcode and then build again?

**Comment by ikzjfr0** [comment]
@osdnk  yes plus deleting whole folder of Xcode/DerivedData and reboot my Macbook

**Comment by ikzjfr0** [comment]
The error is removed after I changed from `#import <React/RCTEventDispatcher.h>` to  `#import "RCTEventDispatcher.h"`. 
However, I don't think it's a good way to do this since I also need to changes hundreds of files from `<React/xxxx.h>` to `"xxxx.h"`

Ideally, i think, it's better to use cocoapod way, rather than react-native link

**Comment by ikzjfr0** [comment]
Seems we supports cocoapod since i can find out this: https://github.com/kmagiera/react-native-gesture-handler/blob/master/ios/RNGestureHandler.podspec

I tried to include following in podfile but got an error after `pod install`:
pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

**Comment by osdnk** [comment]
@ikzjfr0 
I cannot manage to reproduce your issue. 
I made a new project `react-native init`, then:  `yarn add react-native-gesture-handler` and: `react-native link react-native-gesture-handler` and find it workable. 
I also did change versions of react and RN to be exactly same as yours build again the project and everything seems to be fine. Would you like to give me link to repository with sample to project that shows your problem? Would you mind adding version of Xcode you use?

**Comment by osdnk** [comment]
@ikzjfr0 
Maybe [this](https://github.com/kmagiera/react-native-gesture-handler/pull/186) solves your issue?

**Comment by kmagiera** [comment]
@ikzjfr0 I published 1.0.1 that includes #186 

Do you mind trying that to see if it fixes your problem? If so we would like to close this issue.

**Comment by ikzjfr0** [comment]
I still failed to use 'react-native link react-native-gesture-handler` , but managed to use cocoapod: `pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios`.

Moreover, i come to another issue, which may or not be related : https://github.com/react-native-community/react-native-tab-view/issues/408

**Comment by itaydressler** [comment]
Still getting this issue. Did any one solve this?

**Comment by osdnk** [comment]
Could you please try remove your Xcode cache and npm cache as well?

**Comment by hichamnaimi** [comment]
If you are using react-link to link your dependencies:
1/ open your ios Podfile and delete all yout linked dependencies: pod 'xxxxxxx', :path => '../node_modules/xxxxx'
3/ Close Xcode
4/ In your /ios folder run "pod update"
5/ In your project source run "react-native link"
6/ Open Xcode and Clean Build Folder from Xcode Menu -> Product
7/ Run your application from Xcode
8/ Link manually the dependency "react-native-gesture-handler" into your Xcode Project following steps in documentation: https://facebook.github.io/react-native/docs/linking-libraries-ios
9/ Now run your application from Xcode, you should be fine.

**Comment by TomBerriot** [comment]
@hichamnaimi We can't use this solution as Sentry runs a blocking command program when running `react-native link` :/

**Comment by cworsley4** [comment]
@hichamnaimi at which point should we add back our pods?

**Comment by HelloJack0** [comment]
@TomBerriot I have same Podfile.lock, how to resolved it?

**Comment by thiyagarajan13** [comment]
If nothing works try
react-native start --reset-cache
react-native upgrade

**Comment by RONAKDHOLARIYA** [comment]
I try all thing but still not resolved it please help me.

**Comment by AndreyPatseiko** [comment]
+ 1. Have the same problem with RN 0.59.9

**Comment by shyam-unnithan** [comment]
I faced the same issue and have been able to resolve it.
1) Right click your App project in XCode and select "Add files to <project>". Browse to the node_modules/react-native-gesture-handler/ios and Select RNGestureHandler.xcodeproj and click add
2) Then Right click your RNGestureHandler.xcodeproj and select "Add files to RNGestureHander.xcodeproj" and browse to node_modules/react-native/React/ and select React.xcodeproj

Now do a clean in XCode and Build the app. You should now also be able to launch the app using react-native run-ios.

Cheers!

**Comment by hchev001** [comment]
> I faced the same issue and have been able to resolve it.
> 
> 1. Right click your App project in XCode and select "Add files to ". Browse to the node_modules/react-native-gesture-handler/ios and Select RNGestureHandler.xcodeproj and click add
> 2. Then Right click your RNGestureHandler.xcodeproj and select "Add files to RNGestureHander.xcodeproj" and browse to node_modules/react-native/React/ and select React.xcodeproj
> 
> Now do a clean in XCode and Build the app. You should now also be able to launch the app using react-native run-ios.
> 
> Cheers!

@shyam-unnithan Thanks, step 2 solved the issue!

**Comment by douglascavanaugh** [comment]
Okay, here's my conundrum (I have installed all the latest versions of react-native and the herein defined dependencies).  Firstly, I started from the top of this thread and worked my way down trying all suggestions and the result is, my Android works perfectly!  However iOS doesn't.

I've followed the steps outlined by @shyam-unnithan, then:

- When I run `react-native run-ios` I get the following error in the terminal:

`error React Native CLI uses auto linking for native dependencies, but the following modules are linked manually: - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")`

and the build fails:

`'React/RCTEventDispatcher.h' file not found #import <React/RCTEventDispatcher.h>`

- When I run `react-native unlink react-native-gesture-handler`, I noticed that it removes what I did re; @shyam-unnithan in Xcode and if I then attempt to run `react-native run-ios` again, I get the following in the iOS simulator:

`null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')`

- I also noticed in Xcode, under Product>Scheme>Edit Scheme: Build (in left column), React is showing as (Missing) in the Targets view.  I attempt to add it by clicking the plus, but it doesn't show up in the Target List drop down which is also why I can't build it in Xcode as the build fails.  I've tried initializing many new react-native projects and the result is the same due to using React-Navigation and it's dependency React Native Gesture Handler...

**Comment by dsznajder** [comment]
@douglascavanaugh Have you added `use_native_modules!` in your Podfile and run `pod install` after?

**Comment by douglascavanaugh** [comment]
No, but it was already there when I did run `pod install`:
<img width="1163" alt="Screen Shot 2019-07-13 at 6 56 55 PM" src="https://user-images.githubusercontent.com/31994658/61177372-e9a91200-a5a1-11e9-943a-7017d51b8037.png">

And here's the rest of the Podfile:
<img width="1110" alt="Screen Shot 2019-07-13 at 6 58 42 PM" src="https://user-images.githubusercontent.com/31994658/61177380-178e5680-a5a2-11e9-956f-f9a89953dffb.png">

**Comment by denizbas92** [comment]
> @osdnk yes plus deleting whole folder of Xcode/DerivedData and reboot my Macbook



> I faced the same issue and have been able to resolve it.
> 
> 1. Right click your App project in XCode and select "Add files to ". Browse to the node_modules/react-native-gesture-handler/ios and Select RNGestureHandler.xcodeproj and click add
> 2. Then Right click your RNGestureHandler.xcodeproj and select "Add files to RNGestureHander.xcodeproj" and browse to node_modules/react-native/React/ and select React.xcodeproj
> 
> Now do a clean in XCode and Build the app. You should now also be able to launch the app using react-native run-ios.
> 
> Cheers!

Hi,
I have the same issue. Should I add RNGestureHandler.xcodeproj  to Library Folder ?

**Comment by shyam-unnithan** [comment]
> > @osdnk yes plus deleting whole folder of Xcode/DerivedData and reboot my Macbook
> 
> > I faced the same issue and have been able to resolve it.
> > 
> > 1. Right click your App project in XCode and select "Add files to ". Browse to the node_modules/react-native-gesture-handler/ios and Select RNGestureHandler.xcodeproj and click add
> > 2. Then Right click your RNGestureHandler.xcodeproj and select "Add files to RNGestureHander.xcodeproj" and browse to node_modules/react-native/React/ and select React.xcodeproj
> > 
> > Now do a clean in XCode and Build the app. You should now also be able to launch the app using react-native run-ios.
> > Cheers!
> 
> Hi,
> I have the same issue. Should I add RNGestureHandler.xcodeproj to Library Folder ?

Yes

**Comment by samchidi2005** [comment]
I added #import <React/RCTEventDispatcher.h> in the same file and it works with lots of warning.

**Comment by cs-manughian** [comment]
For me, I was able to do the following steps to get the build to succeed:
1. `yarn upgrade`
2. `cd ios` then `pod install`
3. Clean Build Folder in XCode
4. Build project

**Comment by aaryavrate** [comment]
None of the above works for me. I tried all forms of tricks here, but none of it works.
Tried following:
* Remove the RNlibgesture from Linking Binary
* Unlinking and manually adding to podspec.
* yarn upgrade
* Connect RNGestureHandler.xcodeproj & React.xcodeproj

**Comment by aaryavrate** [comment]
> I faced the same issue and have been able to resolve it.
> 
> 1. Right click your App project in XCode and select "Add files to ". Browse to the node_modules/react-native-gesture-handler/ios and Select RNGestureHandler.xcodeproj and click add
> 2. Then Right click your RNGestureHandler.xcodeproj and select "Add files to RNGestureHander.xcodeproj" and browse to node_modules/react-native/React/ and select React.xcodeproj
> 
> Now do a clean in XCode and Build the app. You should now also be able to launch the app using react-native run-ios.
> 
> Cheers!

In my react-native/React there is no React. xcodeproj.
![image](https://user-images.githubusercontent.com/31395247/146575783-fc85e6b9-a075-4b8e-9974-52985e523d28.png)

My react-native version:
"react-native": "~0.63.4",

**Comment by RupamShaw** [comment]
upgraded platform :ios, '11.0'  to '12.0' in podfile having react-native 63.4 and     "expo": "~41.0.1", 
can't Connect RNGestureHandler.xcodeproj & React.xcodeproj
because n my react-native/React there is no React. xcodeproj.

**Comment by owencraston** [comment]
I am still getting this error on my M1 Macbook with `React Native 0.66.` and `"react-native-gesture-handler": "^1.10.3",`

**Comment by owencraston** [comment]
I tried various ways of cleaning and reinstalling as well as deleting Xcode derived data and nothing worked. What fixed it for me was...
```
cd ios
pod deintegrate
pod setup
pod install
```

**Comment by owencraston** [comment]
I am sad to report that this hasn't solved my problem. It worked a few times but not every time. 

> I tried various ways of cleaning and reinstalling as well as deleting Xcode derived data and nothing worked. What fixed it for me was...
> 
> ```
> cd ios
> pod deintegrate
> pod setup
> pod install
> ```

**Comment by owencraston** [comment]
My issue was a tad different as my error occurred inside the `react-native-view-pager` package. I was able to get passed this issue by running `pod update` inside my ios directory. I also updated my cocoapods version to `CocoaPods: 1.12.1` with `sudo gem install cocoapods` but I don't think this was needed.

**Comment by vashusoni** [comment]
Just change **RCTEventDispatcher** to **RCTEventDispatcherProtocol** 
in RCTVideoManager.swift file
