### ISSUE TITLE
react-native@0.59.x Cannot use 'in' operator to search for '__isNative' in null

### ISSUE THREAD

**Issue by alvin-toffler** [kmagiera/react-native-gesture-handler#571]
Hi,

These are my dependencies:

```
"react": "16.6.3",
 "react-native": "0.58.6",
 "react-native-gesture-handler": "^1.1.0",
 "react-navigation": "^3.8.1",
```

When I upgrade to react-native@0.59.x and react@16.8.3, with no code changes, I get this error:

```
TypeError: Cannot use 'in' operator to search for '__isNative' in null
```

I haven't been able to make a reproducible demo, but I have tested 0.59.0, 0.59.1, and 0.59.4 and hit this issue. Downgrading resolves it. 

![Breakpoint in Chrome debugger](https://user-images.githubusercontent.com/43940184/56329572-ff40a400-6138-11e9-99fb-0f55e264ea38.png)

**Comment by mizerlou** [comment]
`yarn add https://github.com/kmagiera/react-native-gesture-handler.git#master` fixes this issue for me...

it was fixed by https://github.com/kmagiera/react-native-gesture-handler/commit/0a2fd0d753f3dc9a4dea7d61ea6a18cc878a54a1

**Comment by Mileshosky** [comment]
Seeing this issue as well on `0.59.4`
I'll be downgrading to attempt resolving

**Comment by alvin-toffler** [comment]
@mizerlou This change does not fix the issue when param === null.

**Comment by osdnk** [comment]
Fixed in the new version

**Comment by EddieEJ** [comment]
@osdnk Can [param is not an Object (evaluating "__isNative" in param')](https://github.com/kmagiera/react-native-gesture-handler/issues/615) be related to this issue?
