### ISSUE TITLE
Warning: Accesing view manager configs for getConstants

### ISSUE THREAD

**Issue by ABulnes** [kmagiera/react-native-gesture-handler#742]
When using RNGH 1.4.1 with RN 0.60 the following warning appears: 

`Accessing view manager configs directly off UIManager via UIManager['getConstants'] is no longer supported. Use UIManager.getViewManagerConfig('getConstants') instead.`

The stack trace points at `createHandler.js:39`

**Comment by giautm** [comment]
Same warning here, Expo SDKv34

**Comment by drnachio** [comment]
Any idea how I can we fix this?

**Comment by ABulnes** [comment]
What i did was to change from expo to react-native init and the errror was gone

**Comment by hardrese7** [comment]
hey guys, just downgrade react-native-gesture-handler to 1.3.0.

You can directly change version in your package.json to `~1.3.0` or remove it and install through expo how described [here](https://github.com/expo/expo/issues/5107#issuecomment-516419810)

**Comment by kimihiro64** [comment]
This was introduced with [this commit](https://github.com/kmagiera/react-native-gesture-handler/commit/c033d98b55171744408fbfe50e5b8113ee56fdbc#diff-88fa64c878efe14d137f130ddbe000a5).

It's not immediately clear whether overwriting UIManager.getConstants is even the right approach now that getViewManagerConfig is used... presumably to keep backwards compatibility you'd have to do both, but do a version check to prevent the warning on RN 60+.

**Comment by douglaszaltron** [comment]
+1

**Comment by mauricioblum** [comment]
+1

**Comment by DiegoMGar** [comment]
Hi, we have any suggestions of how to fix this?

**Comment by Gl0ntz** [comment]
+1 same warning 
Downgrading react-native-gesture-handler does not work for me.

**Comment by DiegoMGar** [comment]
I fixed my project, as I am using expo, installing this package with expo install, this downgraded mine at my package.json to 1.3.* from 1.4.* and now it works as it should.

**Comment by f-luk** [comment]
Remove react-native-gesture-handler with npm / yarn and install through expo how described [her](https://github.com/expo/expo/issues/5107#issuecomment-516419810) like @hardrese7 said

**Comment by byCedric** [comment]
For anyone using Expo, @notbrent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57). (_as of writing, it's `~1.3.0`, note the `~`).

But for those who want a quick fix, here are some commands that you can run to fix it.

```bash
// make sure you have the latest expo-cli (if you have 3.1.0, you can skip this)
$ npm install -g expo@latest

// remove your node_modules and package-lock.json (just to be sure)
$ rm -rf node_modules package-lock.json

// check if you have `react-native-gesture-handler` listed already (if so **remove it**)
$ cat package.json | grep react-native-gesture-handler

// use expo to install the appropriate version
$ expo install react-native-gesture-handler

// start expo with a clean cache
$ expo start --clear
```

**Comment by OnurErtugral** [comment]
This worked for me:

1) npm uninstall  react-native-gesture-handler  
2) npm i react-native-gesture-handler@~1.3.0

**Comment by damechen** [comment]
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57). (_as of writing, it's `~1.3.0`, note the `~`_).
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have 3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

It worked for me. Thanks!

**Comment by expiante** [comment]
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57). (_as of writing, it's `~1.3.0`, note the `~`_).
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have 3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

Also worket for me, Thank you!

**Comment by naveedahmed986** [comment]
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57). (_as of writing, it's `~1.3.0`, note the `~`_).
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

This solution worked for me. Thank alot.
expo-cli : 3.1.0
react-navigation : 4.0.8
react-native-gesture-handler: 1.3.0

**Comment by brunobmello25** [comment]
> > For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57). (_as of writing, it's `~1.3.0`, note the `~`_).
> > But for those who want a quick fix, here are some commands that you can run to fix it.
> > ```shell
> > // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> > $ npm install -g expo@latest
> > 
> > // remove your node_modules and package-lock.json (just to be sure)
> > $ rm -rf node_modules package-lock.json
> > 
> > // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> > $ cat package.json | grep react-native-gesture-handler
> > 
> > // use expo to install the appropriate version
> > $ expo install react-native-gesture-handler
> > 
> > // start expo with a clean cache
> > $ expo start --clear
> > ```
> 
> This solution worked for me. Thank alot.
> expo-cli : 3.1.0
> react-navigation : 4.0.8
> react-native-gesture-handler: 1.3.0

And what is your expo version?

**Comment by tafelito** [comment]
version 1.3.0 of `react-native-gesture-handler` does not support web and you can't use Touchables and also you get all the warnings that web is not supported

**Comment by josermorales** [comment]
> hey guys, just downgrade `react-native-gesture-handler` to `1.3.0`.
> 
> You can directly change version in your `package.json` to `~1.3.0` and run `npm i`/`yarn` or remove it and install through expo how described [here](https://github.com/expo/expo/issues/5107#issuecomment-516419810)

I knew this alias was gonna be handy sometime
```shell
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
```

**Comment by baghel95** [comment]
I'm using expo SDK version: "34.0.0"
and react-native-gesture-handler v 1.4.1 then I get warning,
use npm i react-native-gesture-handler@1.3.0 this worked

**Comment by SAABoy** [comment]
> Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁
> 
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> 
> > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

This solution worked for me. Thanks.
expo-cli : 3.3.0
react-navigation : ^3.11.0
react-native-gesture-handler: ~1.2.1

**Comment by yoinch** [comment]
> hey guys, just downgrade `react-native-gesture-handler` to `1.3.0`.
> 
> You can directly change version in your `package.json` to `~1.3.0` and run `npm i`/`yarn` or remove it and install through expo how described [here](https://github.com/expo/expo/issues/5107#issuecomment-516419810)

When you downgrade, it stops the `react-native-gesture-handler` Buttons from working

**Comment by diamont1001** [comment]
mark.
waiting for a new version to fix it.

**Comment by atifgulzar** [comment]
> Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁
> 
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> 
> > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```




This solution worked for me. Thanks.

expo install react-native-gesture-handler ( This command install the same version ~1.3.0 for me ) but I guess running this command expo start --clear do the trick. :)

expo: ^35.0.0
react-navigation : ^4.0.10
react-native-gesture-handler: ~1.3.0

**Comment by vmheijke** [comment]
> 
> 
> Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁
> 
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> 
> > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

Although using expo install above npm install solved a lot for me in other projects (thanks) i still have this issue. Even if i start a brand new expo-cli 3.4.4. project, I need to add gesture-handler since I want to use react-navigation and react-navigation-stack. 

>     "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.4"

**Comment by kimihiro64** [comment]
Any fix coming for people who /aren't/ using expo?

**Comment by devohno** [comment]
> Remove react-native-gesture-handler with npm / yarn and then `expo install react-native-gesture-handler` like @hardrese7 said
> 
> Compile..

It works for me. Thank you.

**Comment by tonkunz** [comment]
> hey guys, just downgrade `react-native-gesture-handler` to `1.3.0`.
> 
> You can directly change version in your `package.json` to `~1.3.0` and run `npm i`/`yarn` or remove it and install through expo how described [here](https://github.com/expo/expo/issues/5107#issuecomment-516419810)

Same for me... thank's

**Comment by itstrevinooo** [comment]
> Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁
> 
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> 
> > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

This worked for me, thanks!

**Comment by devohno** [comment]
> > Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁
> > For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> > > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> > 
> > 
> > But for those who want a quick fix, here are some commands that you can run to fix it.
> > ```shell
> > // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> > $ npm install -g expo@latest
> > 
> > // remove your node_modules and package-lock.json (just to be sure)
> > $ rm -rf node_modules package-lock.json
> > 
> > // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> > $ cat package.json | grep react-native-gesture-handler
> > 
> > // use expo to install the appropriate version
> > $ expo install react-native-gesture-handler
> > 
> > // start expo with a clean cache
> > $ expo start --clear
> > ```
> 
> This worked for me, thanks!

Thanks. it helped me.
When I install same version of this module with `npm` or `yarn`, it still showed to me a same error message.
However, the error is no longer did not appear when I install the `Expo`.

**Comment by JaimeRamos99** [comment]
first run:
expo install react-native-gesture-handler
then run:
expo start --clear

**Comment by AntMooreWebDev** [comment]
> first run:
> expo install react-native-gesture-handler
> then run:
> expo start --clear

This did it for me. I _had_ to run `expo start --clear` to clear the issue, after running the `expo install` command.

**Comment by Uttu316** [comment]
> Downgrading react-native-gesture-handler to 1.3.0 didn't work for me :-(

I have the same version ~1.3.0 but still getting the error.

**Comment by Uttu316** [comment]
> Downgrading react-native-gesture-handler to 1.3.0 didn't work for me :-(

did you find the solution?

**Comment by rada2292** [comment]
**This work for me**,
First, delete the `node_modules` folder, then change the version of the handler in dependences inside `package.json` like this:
`"react-native-gesture-handler": "1.3.0"`

After that, only run `npm install` and done.

Fixed

**Comment by georgecirilo** [comment]
For me downgrading RNGH version did not solve the problem. This is the manual fix that fixed it for me: 
Go to ./node-modules/react-native-gesture-handler/createHandler.js and replace the following):

```
if (UIManager.getConstants) {
  UIManager.getConstants().genericDirectEventTypes = {
    ...UIManager.getConstants().genericDirectEventTypes,
    ...customGHEventsConfig,
  };
}
```

to:

```
if (UIManager.getViewManagerConfig('getConstants')) {
  UIManager.getViewManagerConfig('getConstants').genericDirectEventTypes = {
    ...UIManager.getViewManagerConfig('getConstants').genericDirectEventTypes,
    ...customGHEventsConfig,
  };
}
```


Basically we're doing what the yellow message warned. Hope this help. 

Note: this fix might be ignored by your git repo.

**Comment by dperez132213** [comment]
> first run:
> expo install react-native-gesture-handler
> then run:
> expo start --clear

This worked for me, thanks!

**Comment by Zlatanius** [comment]
> Edit, [you can now use](https://github.com/expo/expo-cli/issues/1054) `expo install react-native-gesture-handler`. It will take care of everything I listed below. 😁 (Don't forget to clean your cache with `expo start --clear`)
> 
> For anyone using Expo, brent pointed out a way to fix it. Basically, you need to install [the specific versions listed here](https://github.com/expo/expo/blob/291fa2dd715f5e23eace30ae506b715b8dda1929/packages/expo/bundledNativeModules.json#L57).
> 
> > As of writing, the version required is `~1.3.0`. Because NPM doesn't play nice with the tilde (`~`) you might have to edit it manually in your `package.json`.
> 
> But for those who want a quick fix, here are some commands that you can run to fix it.
> 
> ```shell
> // make sure you have the latest expo-cli (if you have >=3.1.0, you can skip this)
> $ npm install -g expo@latest
> 
> // remove your node_modules and package-lock.json (just to be sure)
> $ rm -rf node_modules package-lock.json
> 
> // check if you have `react-native-gesture-handler` listed already (if so **remove it**)
> $ cat package.json | grep react-native-gesture-handler
> 
> // use expo to install the appropriate version
> $ expo install react-native-gesture-handler
> 
> // start expo with a clean cache
> $ expo start --clear
> ```

This actually worked. I cant believe it.

**Comment by stevenriok** [comment]
> For me downgrading RNGH version did not solve the problem. This is the manual fix that fixed it for me:
> Go to ./node-modules/react-native-gesture-handler/createHandler.js and replace the following):
> 
> ```
> if (UIManager.getConstants) {
>   UIManager.getConstants().genericDirectEventTypes = {
>     ...UIManager.getConstants().genericDirectEventTypes,
>     ...customGHEventsConfig,
>   };
> }
> ```
> 
> to:
> 
> ```
> if (UIManager.getViewManagerConfig('getConstants')) {
>   UIManager.getViewManagerConfig('getConstants').genericDirectEventTypes = {
>     ...UIManager.getViewManagerConfig('getConstants').genericDirectEventTypes,
>     ...customGHEventsConfig,
>   };
> }
> ```
> 
> Basically we're doing what the yellow message warned. Hope this help.
> 
> Note: this fix might be ignored by your git repo.

Thanks Mate, it's better solution than others

**Comment by rogger-frogger** [comment]
For those who cannot downgrade the library, you can hide the warning by doing:

`YellowBox.ignoreWarnings(['Accessing view manager configs directly off UIManager via UIManager[\'getConstants\'] is no longer supported. Use UIManager.getViewManagerConfig(\'getConstants\') instead.']);`
